spring:
  datasource:
    url: jdbc:mysql://localhost/db_products
    username: ${USER_DB}
    password: ${USER_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true